# **Programming for Artificial Intelligence Assignment 2**

### Name: Mohammad Yesaullah Sheikh
### Roll no: 23k-0019

In [1]:
import numpy as np;

# **Task 1:**

In [2]:
array1 = np.arange(1, 11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Sum

In [4]:
sum = np.sum(array1)
print(sum)

55


### Mean

In [5]:
mean = np.mean(array1)
print(mean)

5.5


### Product

In [6]:
product = np.prod(array1)
print(product)

3628800


# **Task 2:**

In [8]:
array3x3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
transpose = np.transpose(array3x3)
print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# **Task 3:**

In [10]:
array3 = np.random.randint(1, 100, size=20)
array3

array([ 1, 55, 33, 78, 71, 63, 13, 34, 13, 71, 58, 12, 47,  5,  8, 19, 82,
       15, 67,  3], dtype=int32)

In [12]:
array3 = array3.reshape((4, 5))
array3

array([[ 1, 55, 33, 78, 71],
       [63, 13, 34, 13, 71],
       [58, 12, 47,  5,  8],
       [19, 82, 15, 67,  3]], dtype=int32)

# **Task 4:**

In [17]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

### Element-wise sum

In [18]:
sum_arr = arr1 + arr2
sum_arr

array([11, 22, 33, 44, 55])

### Element-wise subtraction

In [19]:
subtraction_arr = arr1 - arr2
subtraction_arr

array([ -9, -18, -27, -36, -45])

### Element-wise multiplication

In [20]:
product_arr = arr1*arr2
product_arr

array([ 10,  40,  90, 160, 250])

### Element-wise division

In [21]:
division_arr = arr1/arr2
division_arr

array([0.1, 0.1, 0.1, 0.1, 0.1])

# **Task 5:**

In [23]:
array5 = np.random.randint(1, 101, size=10)
array5

array([18, 97, 71,  3, 54, 99,  2, 73, 89, 15], dtype=int32)

In [24]:
sqrt = np.sqrt(array5)
sqrt

array([4.24264069, 9.8488578 , 8.42614977, 1.73205081, 7.34846923,
       9.94987437, 1.41421356, 8.54400375, 9.43398113, 3.87298335])

# **Task 6:**

In [26]:
arr2x2 = np.matrix([
    [3, 5],
    [6, 8]
])
arr2x2

matrix([[3, 5],
        [6, 8]])

### Determinant

In [27]:
determinent = np.linalg.det(arr2x2)
determinent

np.float64(-6.0)

### Inverse

In [28]:
inverse = np.linalg.inv(arr2x2)
inverse

matrix([[-1.33333333,  0.83333333],
        [ 1.        , -0.5       ]])

# **Task 7:**

In [30]:
arr7 = np.random.randint(1, 101, size=50)
arr7

array([62, 43, 91,  9, 29, 27, 59, 15, 52, 98, 53, 15, 42, 97, 75, 63, 65,
       92, 67, 38, 42,  1, 99, 16, 23, 43, 73, 69, 74,  4, 72,  3, 94,  2,
       69, 36, 22, 80, 57, 62, 91, 98, 56, 63, 87, 15, 97, 76, 91, 20],
      dtype=int32)

### Maximum

In [33]:
maxindex = np.argmax(arr7)
print(maxindex)

22


### Minimum

In [34]:
minindex = np.argmin(arr7)
print(minindex)

21


# **Task 8:**

In [35]:
A = np.array([
    [3, 2, -1],
    [2, -2, 4],
    [-1, 0.5, -1]
])
B = np.array([1, -2, 0])

In [37]:
X = np.linalg.solve(A, B)
print(X)

[ 1. -2. -2.]


# **Task 9:**

In [42]:
arr9 = np.random.randint(1, 101, size=25)
arr9

array([30, 87, 16, 68, 11, 14, 90, 57, 13, 95, 47, 10, 70, 40, 97, 98, 29,
       59, 68, 89, 35, 91, 93, 78, 36], dtype=int32)

In [44]:
percentile = np.percentile(arr9, 75)
print(percentile)

89.0


# **Task 10:**

In [45]:
def normalizer(array):
    mean = np.mean(array)
    std_dev = np.std(array)
    normalized_arr = (array-mean) / std_dev
    return normalized_arr

In [47]:
arr10 = np.array([1, 2, 3, 4, 5])
normalized_arr = normalizer(arr10)
normalized_arr

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])